modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="Ellada" #mandatory
#logoFile="examplemod.png"
credits="Thanks go to NUDLAUFLAUCH and AGENT BROKKOLI 007 for all of the textures"
authors="Stehschnitzel"
description='''
Adds a new Biome with a greek theme
'''


[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true

    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    mandatory=true

    versionRange="${terrablender_version_range}"
    ordering="NONE"
    side="BOTH"