modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods" #optional

[[mods]] #mandatory

modId="ellada" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ellada" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks go to NUDLAUFLAUCH and AGENT BROKKOLI 007 for all of the textures" #optional
authors="Stehschnitzel" #optional
description='''

Cheesus makes Cheese

'''


[[dependencies.ellada]]
    modId="minecraft"
    mandatory=true
   
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"